name: Build Mobile

on:
  workflow_dispatch:

jobs:
  build-sign-ios:
    name: Build iOS (Unsigned)
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install dependencies & Codegen
        run: |
          cd mobile
          flutter pub get
          dart run slang

      - name: Build Unsigned IPA
        run: |
          cd mobile
          flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa-unsigned
          path: mobile/build/ios/archive/Runner.xcarchive